"""add foreign key constraints to reviews

Revision ID: 6da646d7dc7e
Revises: 9f5d82439ecf
Create Date: 2025-03-19 17:01:54.100110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da646d7dc7e'
down_revision = '9f5d82439ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_reviews_customer_id_customers', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_item_id_items', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_item_id_items', 'reviews', 'items', ['item_id'], ['id'])
    op.create_foreign_key('fk_reviews_customer_id_customers', 'reviews', 'customers', ['customer_id'], ['id'])
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
